### ISSUE TITLE
Missing Value Handling

### ISSUE THREAD

**Issue by frederikpahde** [Fred93/BADS#2]
Missing Data Imputation and Model Checking:
https://cran.r-project.org/web/packages/mi/mi.pdf

**Comment by Fred93** [comment]
Missing Data Imputation and Model Checking:
https://cran.r-project.org/web/packages/mi/mi.pdf

**Comment by frederikpahde** [comment]
https://cran.r-project.org/web/packages/imputeR/imputeR.pdf

**Comment by frederikpahde** [comment]
https://cran.r-project.org/web/packages/Hmisc/Hmisc.pdf (currently used)
- "impute" for simple static imputation
- "transcan" for more sophisticated imputation (consider in 2nd iteration)
