### ISSUE TITLE
Feature Selection (Dimensionality Reduction I)

### ISSUE THREAD

**Issue by frederikpahde** [Fred93/BADS#3]

**Comment by Selina91** [comment]
Package for logistic regression (feature selection included):
https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiOq6OWxd3JAhXBfA8KHSY0DCQQFggnMAE&url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fpackages%2Fglmnet%2Fglmnet.pdf&usg=AFQjCNHD0IZj-9vEiIgHFfuVDzXON_yxUA&sig2=yu-9zly_vrzE6almSUyKMA&bvm=bv.110151844,d.ZWU
